project:
  type: website
  output-dir: docs
website:
  title: "Aidan Berg"
  site-url: https://aidanberg.us/
  description: "Data science, professional portfolio, and personal musings"
  navbar:
    right:
      - blog.qmd
      - icon: rss
      - href: sitemap.xml
      - icon: github
        href: https://github.com/Aidan-Berg
      - icon: linkedin
        href: https://www.linkedin.com/in/aidan-berg-epi/
format:
  html:
    theme: flatly
    css: styles.css

editor: source

